---
- name: Create IDS Connection Limit profiles on all devices
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml

  vars:
    dp_ip:
      - "10.105.192.32"
      - "10.105.192.33"

    connection_limit_setting:
      Connection Limit Attack Protocol: "3"
      Connection Limit Attack Threshold: "50"
      Connection Limit Attack Tracking Type: "2"
      Connection Limit Attack ReportMode: "10"
      Connection Limit Attack PacketReport: "2"
      Connection Limit Attack Risk: "3"
      Connection Limit Attack Type: "1"

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Create IDS Connection Limit profile on each device
          loop: "{{ dp_ip }}"
          loop_control:
            label: "{{ item }} / Test_CL2"
          create_cl_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            name: "Test_CL2"
            params: "{{ connection_limit_setting }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
