---
- name: Create OOS Stateful profiles on all devices
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/cc.yml   # CC connection details + profiles

  tasks:
    - block:
        - name: Lock device(s) before configuration
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Create OOS Stateful profiles on each device
          vars:
            profile_matrix: "{{ dp_ip | product(oos_mapping) | list }}"
          loop: "{{ profile_matrix }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1.name }}"
          create_oos_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            name: "{{ item.1.name }}"
            params: "{{ item.1.params }}"

      always:
        - name: Unlock device(s) after configuration
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
