---
- name: Create OOS/Stateful profiles only
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml

  vars:
    dp_ip:
      - "10.105.192.32"
      - "10.105.192.33"

    # Stateful / OOS profile defaults
    stateful_defaults:
      rsSTATFULProfileactThreshold: "5000"
      rsSTATFULProfiletermThreshold: "4000"
      rsSTATFULProfilesynAckAllow: "1"
      rsSTATFULProfilePacketTraceStatus: "1"
      rsSTATFULProfilePacketReportStatus: "1"
      rsSTATFULProfileRisk: "2"
      rsSTATFULProfileAction: "1"

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Create OOS/Stateful profile on each device
          loop: "{{ dp_ip }}"
          loop_control:
            label: "{{ item }} / Test1"
          dp_oos_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            name: "Test1"
            params: "{{ stateful_defaults }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
