---
- name: Create HTTP Profiles on Radware Devices
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml   # Provider/device login details

  vars:
    dp_ip:
      - "10.105.192.32"
      - "10.105.192.33"

    http_profiles:
      - name: "HTTP_Profile1"
        max_connections: 1000
        timeout: 30
      - name: "HTTP_Profile2"
        max_connections: 500
        timeout: 20

  tasks:

    - name: Lock device(s)
      dp_lock:
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
      loop: "{{ dp_ip }}"

    - name: Create HTTP profiles on devices
      dp_http_profile:
        host: "{{ item.0 }}"
        name: "{{ item.1.name }}"
        max_connections: "{{ item.1.max_connections }}"
        timeout: "{{ item.1.timeout }}"
      loop: "{{ dp_ip | product(http_profiles) | list }}"
      loop_control:
        label: "{{ item.1.name }} on {{ item.0 }}"

    - name: Unlock device(s)
      dp_unlock:
        host: "{{ item }}"
        username: "{{ username }}"
        password: "{{ password }}"
      loop: "{{ dp_ip }}"
