---
- name: Create HTTPS Flood profiles only
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml

  vars:
    dp_ip:
      - "10.105.192.32"
      - "10.105.192.33"

    # HTTPS Flood profile defaults
    https_defaults:
      rsHttpsFloodProfileAction: "1"
      rsHttpsFloodProfileRateLimit: "100"
      rsHttpsFloodProfileSelectiveChallenge: "2"
      rsHttpsFloodProfileCollectiveChallenge: "2"
      rsHttpsFloodProfileChallengeMethod: "2"
      rsHttpsFloodProfileRateLimitStatus: "1"
      rsHttpsFloodProfileFullSessionDecryption: "2"

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Create HTTPS Flood profile on each device
          loop: "{{ dp_ip }}"
          loop_control:
            label: "{{ item }} / HTTPS_Demo1"
          dp_http_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            name: "HTTPS_Demo1"
            params: "{{ https_defaults }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
