---
- name: Create HTTPS Flood profiles on all devices
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml

  vars:
    dp_ip:
      - "10.105.192.32"
      - "10.105.192.33"

    http_setting:
      rsHttpsFloodProfileAction: "1"
      rsHttpsFloodProfileRateLimit: "100"
      rsHttpsFloodProfileSelectiveChallenge: "2"
      rsHttpsFloodProfileCollectiveChallenge: "2"
      rsHttpsFloodProfileChallengeMethod: "2"
      rsHttpsFloodProfileRateLimitStatus: "1"
      rsHttpsFloodProfileFullSessionDecryption: "2"

    https_profiles:
      - name: "HTTPS_Demo1"

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Create HTTPS Flood profile on each device
          vars:
            profile_matrix: "{{ dp_ip | product(https_profiles) | list }}"
          loop: "{{ profile_matrix }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1.name }}"
          create_http_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            name: "{{ item.1.name }}"
            params: "{{ http_setting }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
