---
- name: Configure HTTP/S profile on multiple devices
  hosts: CyberController
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
  vars:
    devices:
      - 10.105.192.32
      - 10.105.192.33
    http_profile:
      name: "HTTPS_Demo1"
      settings:
        rsHttpsFloodProfileName: "HTTPS_Demo1"
        rsHttpsFloodProfileAction: "1"
        rsHttpsFloodProfileRateLimit: "100"
        rsHttpsFloodProfileSelectiveChallenge: "2"
        rsHttpsFloodProfileCollectiveChallenge: "2"
        rsHttpsFloodProfileChallengeMethod: "2"
        rsHttpsFloodProfileRateLimitStatus: "1"
        rsHttpsFloodProfileFullSessionDecryption: "2"

  tasks:
    - name: Lock device
      dp_lock:
        provider: "{{ cc }}"
        device_ip: "{{ item }}"
      loop: "{{ devices }}"
      loop_control:
        label: "{{ item }}"

    - name: Create HTTP/S profile
      dp_http_profile:
        provider: "{{ cc }}"
        device_ip: "{{ item }}"
        profile_name: "{{ http_profile.name }}"
        profile: "{{ http_profile.settings }}"
      loop: "{{ devices }}"
      loop_control:
        label: "{{ item }}"

    - name: Unlock device
      dp_unlock:
        provider: "{{ cc }}"
        device_ip: "{{ item }}"
      loop: "{{ devices }}"
      loop_control:
        label: "{{ item }}"
