---
- name: Create Traffic Filter profiles and protections
  hosts: cc
  gather_facts: false
  vars_files:
    - ../vars/cc.yml
    - ../vars/create_vars.yml

  tasks:
    - name: Create and apply Traffic Filter configuration
      block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip | default([]) }}"
          loop_control:
            label: "Locking device: {{ item }}"
          when: not (skip_device_lock | default(false))

        - name: Configure Traffic Filter profiles and protections
          create_traffic_filter:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            tf_profiles: "{{ create_tf_profiles | default([]) }}"
            tf_protections: "{{ create_tf_protections | default([]) }}"
          loop: "{{ dp_ip | default([]) }}"
          loop_control:
            label: "Device: {{ item }}"
          register: tf_create_results
          when: (create_tf_profiles is defined and create_tf_profiles | length > 0) or
                (create_tf_protections is defined and create_tf_protections | length > 0)

        - name: Display Traffic Filter creation results
          vars:
            response: "{{ item.response | default({}) }}"
            formatted_output: |
              **Device: {{ item.item }}**

              EXECUTION RESULTS:

              {% if create_tf_profiles is not defined and create_tf_protections is not defined %}
                there is no variable
              {% else %}
                **Traffic Filter Profiles created successfully:**
                {{ response.pretty_profiles | default('No profiles created') }}

                **Traffic Filter Protections created successfully:**
                {{ response.pretty_protections | default('No protections created') }}

                **Errors Detected:**
                {% if response.errors | length > 0 %}
                - {{ response.errors | join('\n- ') }}
                {% else %}
                No errors detected.
                {% endif %}
              {% endif %}
          ansible.builtin.debug:
            msg: "{{ formatted_output.split('\n') }}"
          loop: "{{ tf_create_results.results | default([]) }}"
          loop_control:
            label: "Device: {{ item.item }}"

        - name: Apply Traffic Filter updates per device
          update_policies:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip | default([]) }}"
          loop_control:
            label: "Applying updates: {{ item }}"
          when:
            - not (skip_policy_updates | default(false))
            - tf_create_results is defined
            - tf_create_results.changed | default(false)

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip | default([]) }}"
          loop_control:
            label: "Unlocking device: {{ item }}"
          failed_when: false
          when: not (skip_device_lock | default(false))
