---
- name: Create OOS profiles
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/create_vars.yml

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_device_lock | default(false))

        - name: Configure OOS profiles
          create_oos_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            oos_profiles: "{{ oos_profiles | default([]) }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Device: {{ item }}"
          register: OOS_create_results

        - name: Display OOS creation results
          vars:
            formatted_output: |
              Device: {{ item.item }}
              {% if item.response.preview_mode | default(false) %}
              PREVIEW MODE - Operations that would be performed:
              {% set planned_ops = item.response.planned_operations | default([]) %}
              {% if planned_ops %}
              
              OOS Profile Creations ({{ planned_ops | length }} planned):
              {% for op in planned_ops %}
                - {{ op.profile_name }}
              {% endfor %}
              {% else %}
              
              No OOS profiles configured for creation.
              {% endif %}
              {% elif ansible_check_mode %}
              PREVIEW MODE - Operations that would be performed:
              
              OOS Configurations ({{ item.debug_info.input.profiles_count | default(0) }} profiles):
              {% if item.debug_info.input.profiles_count | default(0) > 0 %}
                - {{ item.debug_info.input.profiles_count }} profile(s) would be created
              {% endif %}
              {% else %}
              EXECUTION RESULTS:
              {% if item.failed | default(false) %}
              
              Error occurred during creation:
                - {{ item.msg | default('Unknown error') }}
              {% elif item.debug_info.input.profiles_count | default(0) > 0 %}
              
              OOS Profiles created successfully:
                - {{ item.debug_info.input.profiles_count }} profile(s) created
              {% else %}
              
              No OOS profiles were created.
              {% endif %}
              {% endif %}
          debug:
            msg: "{{ formatted_output.split('\n') }}"
          loop: "{{ OOS_create_results.results }}"
          loop_control:
            label: "Device: {{ item.item }}"

        - name: Apply policy updates per device
          update_policies:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Applying policies: {{ item }}"
          when: 
            - not (skip_policy_updates | default(false))
            - OOS_create_results is defined
            - OOS_create_results.changed | default(false)

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_device_lock | default(false))
