---
- name: Create and Attach SYN Protections to Profiles
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/create_syn_vars.yml   # ✅ Added external vars file

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Create SYN Protections
          vars:
            protection_matrix: "{{ dp_ip | product(syn_mappings) | list }}"
          loop: "{{ protection_matrix }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1.protection_name }}"
          create_syn_protection:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            name: "{{ item.1.protection_name }}"
            params: "{{ item.1.protection_params }}"
          register: protection_results
          failed_when: >
            protection_results is failed and
            ('already exist' not in (protection_results.msg | default('')))

        - name: Attach Protections to SYN Profiles
          vars:
            profile_matrix: "{{ dp_ip | product(syn_mappings) | list }}"
          loop: "{{ profile_matrix }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1.profile_name }}/{{ item.1.protection_name }}"
          create_syn_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            profile_name: "{{ item.1.profile_name }}"
            protection_name: "{{ item.1.protection_name }}"
            params: "{{ item.1.profile_params }}"
          register: profile_results
          failed_when: >
            profile_results is failed and
            ('already exists' not in (profile_results.msg | default('')) and
             'same key already exists' not in (profile_results.msg | default('')))

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
