---
- name: Create HTTPS Flood profiles on all devices
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml  # CC connection details

  vars:
    # List of DefensePro device IPs
    dp_ip:
      - "10.105.192.32"
      - "10.105.192.33"

    # Multiple HTTPS Flood profiles with unique parameters
    https_profiles:
      - name: "HTTPS_Profile_1"
        params:
          Profile Action: "block & report"        # report / block & report
          Rate Limit: "100000"                    # Max packets per second
          Selective Challenge: "enable"
          Collective Challenge: "enable"
          Challenge Method: "httpRedirect"        # javaScript / httpRedirect
          Rate Limit Status: "disable"
          Full Session Decryption: "disable"

      - name: "HTTPS_Profile_2"
        params:
          Profile Action: "report"
          Rate Limit: "50000"
          Selective Challenge: "disable"
          Collective Challenge: "enable"
          Challenge Method: "javaScript"
          Rate Limit Status: "enable"
          Full Session Decryption: "enable"

      - name: "HTTPS_Profile_3"
        params:
          Profile Action: "block & report"
          Rate Limit: "75000"
          Selective Challenge: "enable"
          Collective Challenge: "disable"
          Challenge Method: "httpRedirect"
          Rate Limit Status: "enable"
          Full Session Decryption: "disable"

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Create HTTPS Flood profiles on each device
          vars:
            profile_matrix: "{{ dp_ip | product(https_profiles) | list }}"
          loop: "{{ profile_matrix }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1.name }}"
          create_http_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            name: "{{ item.1.name }}"
            params: "{{ item.1.params }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
