---
- name: Delete HTTPS Flood profiles on all devices
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml

  vars:
    dp_ip:
      - "10.105.192.32"
      - "10.105.192.33"

    # List of HTTPS profiles to delete
    delete_https_profiles:
      - "HTTPS_Demo1"

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Delete each HTTPS profile on all devices
          loop: "{{ dp_ip | product(delete_https_profiles) | list }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1 }}"
          dp_delete_http_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            name: "{{ item.1 }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

