---
- name: Delete DNS Protection profiles
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/delete_vars.yml  # contains dns_profiles list

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Delete DNS profiles
          delete_dns_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            dns_profiles: "{{ delete_dns_profiles | default([]) }}"
          loop: "{{ dp_ip }}"
          loop_control:
            label: "Device: {{ item }}"
          register: delete_results

        - name: Display deletion results (formatted)
          vars:
            formatted_output: |
              Device: {{ item.item }}

              {% if item.response is defined %}
              EXECUTION RESULTS:

              {% for res in item.response %}
                - Profile: {{ res.profile }}
                  {% if res.failed | default(false) %}
                  Status: FAILED
                  Error: {{ res.response.error | default('Unknown error') }}
                  Response body: {{ res.response }}
                  {% else %}
                  Status: DELETED
                  {% endif %}
              {% endfor %}

              {% if not item.response %}
              No operations performed (no deletions configured).
              {% endif %}
              {% else %}
              No deletion results returned.
              {% endif %}
          debug:
            msg: "{{ formatted_output.split('\n') }}"
          loop: "{{ delete_results.results }}"
          loop_control:
            label: "Device: {{ item.item }}"

        - name: Apply policy updates per device
          update_policies:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
          when: not (skip_policy_updates | default(false))
          loop_control:
            label: "Applying policies: {{ item }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
