---
- name: Edit DNS Protection profile
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/edit_dns_vars.yml

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Edit DNS Protection profiles
          vars:
            profile_matrix: "{{ dp_ip | product(dns_profile) | list }}"
          loop: "{{ profile_matrix }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1.name }}"
          edit_dns_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            name: "{{ item.1.name }}"
            params: "{{ item.1.params }}"

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
