---
- name: Edit HTTP/HTTPS Flood profiles on Radware Devices
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/edit_http_vars.yml

  vars:
    profile_matrix: "{{ dp_ip | product(http_profiles) | list }}"

  tasks:

    - name: Lock all devices
      dp_lock:
        provider: "{{ cc }}"
        dp_ip: "{{ item }}"
      loop: "{{ dp_ip }}"
      loop_control:
        label: "{{ item }}"

    - name: Edit HTTP/HTTPS profiles on devices
      edit_http_profile:
        provider: "{{ cc }}"
        dp_ip: "{{ item.0 }}"
        name: "{{ item.1.name }}"
        params: "{{ item.1.params }}"
      loop: "{{ profile_matrix }}"
      loop_control:
        label: "{{ item.0 }}/{{ item.1.name }}"

    - name: Unlock all devices
      dp_unlock:
        provider: "{{ cc }}"
        dp_ip: "{{ item }}"
      loop: "{{ dp_ip }}"
      loop_control:
        label: "{{ item }}"
