---
- name: Edit Protected SSL Objects on Devices
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/edit_ssl_vars.yml   # 👈 vars for edit task

  tasks:
    - block:
        - name: Lock device(s)
          dp_lock:
            provider:
              cc_ip: "{{ cc.cc_ip }}"
              username: "{{ cc.username }}"
              password: "{{ cc.password }}"
              log_level: "{{ cc.log_level }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Edit SSL Objects
          vars:
            edit_matrix: "{{ dp_ip | product(ssl_objects_to_edit) | list }}"
          loop: "{{ edit_matrix }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1.ssl_object_name }}"
          edit_ssl_object:
            provider:
              cc_ip: "{{ cc.cc_ip }}"
              username: "{{ cc.username }}"
              password: "{{ cc.password }}"
              log_level: "{{ cc.log_level }}"
            dp_ip: "{{ item.0 }}"
            ssl_object_name: "{{ item.1.ssl_object_name }}"
            params: "{{ item.1.params }}"
          register: edit_results

      always:
        - name: Unlock device(s)
          dp_unlock:
            provider:
              cc_ip: "{{ cc.cc_ip }}"
              username: "{{ cc.username }}"
              password: "{{ cc.password }}"
              log_level: "{{ cc.log_level }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"
