---
- name: Retrieve DNS Protection profile
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/get_dns_vars.yml

  tasks:
    - name: Fetch DNS profile
      vars:
        device_profile_matrix: "{{ dp_ip | product(dns_profile) | list }}"
      loop: "{{ device_profile_matrix }}"
      loop_control:
        label: "{{ item.0 }}/{{ item.1.name }}"
      get_dns_profile:
        provider: "{{ cc }}"
        dp_ip: "{{ item.0 }}"
        name: "{{ item.1.name }}"
      register: dns_get_results

    - name: Display retrieved DNS profiles
      debug:
        var: dns_get_results
