---
- name: Fetch DNS profiles from DefensePro
  hosts: cc
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/get_vars.yml   # Contains dp_ip list and filter_dns_profile_names list

  tasks:
    - block:
        # Fetch DNS profiles from devices
        - name: Fetch DNS profiles
          get_dns_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
            filter_dns_profile_names: "{{ filter_dns_profile_names }}"
          loop: "{{ dp_ip }}"
          register: dns_fetch_results
          loop_control:
            label: "Device: {{ item }}"

        # Display fetched DNS profiles (formatted)
        - name: Display DNS profiles (formatted)
          vars:
            formatted_output: |
              {% for result in dns_fetch_results.results %}
              Device: {{ result.item }}
              {% if result.response.formatted_profiles %}
              DNS Profiles Found ({{ result.response.summary.total_entries }} entries):
              {% for profile in result.response.formatted_profiles %}
                Profile Name: {{ profile.profile_name }}
                --------------------------------------------------
                Basic Configuration:
                {% for k, v in profile.items() if k != 'profile_name' %}
                  {{ "%-35s %s" | format(k, v) }}
                {% endfor %}
                --------------------------------------------------
              {% endfor %}

              Summary:
                - Total entries: {{ result.response.summary.total_entries }}
                - Unique profiles: {{ result.response.summary.unique_profiles }}
                - Profile names: {{ result.response.summary.profile_names | join(', ') }}
                - Filter applied: {{ result.response.summary.filtered }}
              {% else %}
              No DNS profiles found or error occurred.
              {% endif %}
              {% endfor %}
          debug:
            msg: "{{ formatted_output.split('\n') }}"
