---
- name: Get specific OOS (Stateful) profiles from all devices
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars/cc.yml
    - ../vars/get_oos_vars.yml   # Contains dp_ip and oos_profiles_to_fetch

  tasks:
    - block:
        - name: Lock device(s) before fetching profiles
          dp_lock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

        - name: Fetch each OOS profile from all devices
          loop: "{{ dp_ip | product(profile_names) | list }}"
          loop_control:
            label: "{{ item.0 }}/{{ item.1 }}"
          get_oos_profile:
            provider: "{{ cc }}"
            dp_ip: "{{ item.0 }}"
            name: "{{ item.1 }}"
          register: oos_profiles_output
          until: oos_profiles_output is success
          retries: 2
          delay: 2

      always:
        - name: Unlock device(s) after fetching profiles
          dp_unlock:
            provider: "{{ cc }}"
            dp_ip: "{{ item }}"
          loop: "{{ dp_ip }}"

    - name: Show OOS profiles
      debug:
        var: oos_profiles_output
